apiVersion: v1
kind: Service
metadata:
  name: impulse-svc
  namespace: impulse
spec:
  type: NodePort
  selector:
    app: impulse
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      nodePort: 30557
