name: Linting & Unit Tests
on:
  pull_request:
    branches: [main]
jobs:
  linting-and-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21.x
      - uses: actions/checkout@v3
      - name: Run linter
        run: gofmt -s -d -e . && test -z $(gofmt -l .)
      - name: Run unit tests
        run: make test
